project_id = "oqwcgvemrvimrdrzjzil"

[functions.facebook-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-embedded-signup]
verify_jwt = false

[functions.whatsapp-oauth-callback]
verify_jwt = false

[functions.whatsapp-api]
verify_jwt = false

[functions.facebook-oauth-callback]
verify_jwt = false

[functions.facebook-get-app-id]
verify_jwt = false
